### ISSUE TITLE
Just a question as to why block some security updates?

### ISSUE THREAD

**Issue by hmscott** [Nummer/Destroy-Windows-10-Spying#151]
Hi, love the app, don't want to bug you, but is there a doc that shows why each KB is blocked, most I can understand, but these 3 I am uncertain about why you are blocking them:

Asked it online here:
http://forum.notebookreview.com/threads/updates-to-hide-to-prevent-windows-10-upgrade-disable-telemetry.780476/page-33#post-10128098

And, here is the text about those 3 KB's removed:

"KB3042058
Microsoft security advisory: Update to default cipher suite priority order: May 12, 2015
https://support.microsoft.com/en-us/kb/3042058
Update to Default Cipher Suite Priority Order
https://technet.microsoft.com/library/security/3042058

KB3088195
MS15-111: Description of the security update for Windows Kernel: October 13, 2015
https://support.microsoft.com/en-us/kb/3088195
Security Update for Windows 7 for x64-based Systems (KB3088195)
http://www.microsoft.com/en-us/download/details.aspx?id=49217&WT.mc_id=rss_windows_allproducts

KB3093983
MS15-106: Security update for Internet Explorer: October 13, 2015
https://support.microsoft.com/en-us/kb/3093983

Any ideas why these are removed by DWS"

Thank you for your hard work :)

Scott

**Comment by smiba** [comment]
It seems there is no need to block these updates, a quick google search gives me either one post saying its bad or a few posts discussing it. There seems to be no proof these updates are malicious

I think they should be unbannend and future versions of DWS should verify if these updates are not banned (by the old versions)

**Comment by Nummer** [comment]
KB3088195 - keylogger (on kernel)
KB3042058 - winlogon spying
KB3093983 - ie spying.

**Comment by Baigle** [comment]
KB3093983 - http://forum.notebookreview.com/threads/updates-to-hide-to-prevent-windows-10-upgrade-disable-telemetry.780476/page-34 (They have a lot of good discussions regarding these assumed bad updates and enjoy your work.)

I, like them, could not find anything definitive against this particular update regarding IE spying and would personally question its being banned. I would love to see something showing that it is malicious, but patching remotely exploitable security vulnerabilities in the crappy IE software should take precedence.

KB3042058 - Adding support for more secure encryption methods that use perfect forward secrecy among other things this update does is a good thing. Since this update applies to server versions of the OS as well. Many corporate users would have noticed Winlogon delivering account info when it wasn't supposed to, or it delivering info improperly. Encryption capabilities like these are necessary for secure Domain logins and with the new protections M$ has implemented against pass the hash vulnerabilities in Windows (a godsend), anything they do to better encryption protocols is OK in my book.

https://technet.microsoft.com/en-us/library/cc780332(v=ws.10).aspx
https://technet.microsoft.com/en-us/library/cc780455(v=ws.10).aspx
https://www.nsa.gov/ia/programs/suiteb_cryptography/
(That last link is just to make some people cringe though they provide usable info.)

KB3088195 - This update fixes 3 security holes in Windows... I really don't know where a kernel keylogger idea came up, but more of these types of updates not getting installed may lead to full system pwnage.

https://technet.microsoft.com/library/security/MS15-111

Likely am missing some information in this post, but just reply and correct me, please. Removing Win10 spying is one thing, but completely undermining the security of Winderps in the process is another.

All in all, as soon as anyone understands what the heck Diagnostics Tracking Service is and why it's in Win7 & 8 its immediately time to switch to Mint or something else besides M$.

**Comment by drTr0jan** [comment]
KB3042058 doesn't update winlogon.exe on Windows 8.1

**Comment by Nummer** [comment]
I'm sorry, I made a mistake with the number of updates.

**Comment by useribs** [comment]
Hi, is it closed? Latest DWS  build 700 still removes KB3042058

**Comment by hmscott** [comment]
Hey Nummer, thanks again for your hard work. :)

I didn't understand your response, can you elaborate?  Like what is the
outcome / result / action of your realization?

"I'm sorry, I made a mistake with the number of updates."

All the patches mentioned in this thread are still being removed in the
latest DWS version 700 I ran yesterday.

KB3088195 - keylogger (on kernel)
KB3042058 - winlogon spying
KB3093983 - ie spying.

"...
[INFO] Latest version number: 700
...
[INFO] Remove update KB3088195
...
[INFO] Remove update KB3093983
...
[INFO] Remove update KB3042058"

Thanks again Nummer :)
