### ISSUE TITLE
not a bug

### ISSUE THREAD

**Issue by amitz1** [Nummer/Destroy-Windows-10-Spying#162]
first thanks for the software it is very useful
i use it to uninstall metro apps and wonder if there is a way to exclude apps from this list.
many of my users use and like the calc app

thanks
Amir

**Comment by Nummer** [comment]
TODO: Add

**Comment by amitz1** [comment]
add the calc after uninstall all?
thanks

**Comment by vpm** [comment]
please add future to delete onedrive from command line
dws_lite.exe /deleteonedrive

**Comment by Nummer** [comment]
![image](https://cloud.githubusercontent.com/assets/7760838/11767104/642c4bc4-a1b3-11e5-8cd8-bd7e3a50df1b.png)

**Comment by Nummer** [comment]
@vpm  
![image](https://cloud.githubusercontent.com/assets/7760838/11767106/74ae6d74-a1b3-11e5-81f4-dac1b9c04c4c.png)

**Comment by vpm** [comment]
I think it should be add to readme

This program destroys spying on Windows 7/8/8.1/10.
The program is open source code, which is on github.
This program completely destroys spying. Removes some elements of telemetry and the other turns off, disables Windows Defender, Cortana, and much more. As the program disables Windows Update, which allows you to remain anonymous and not to receive updates of new spyware.
The delete Metro applications is very good, because they work in the background, and devour memory, and some of them spying on you.
Also, the program blocks many IP address of Microsoft, which are the data, and adds the most spyware to hosts.
Almost all of the program is irreversible and should not be rolled back even after a system restore point.
At the moment it is the most effective program. The program is developing and improving a large community of users of Windows 10, some help to rewrite the code to a more productive, and some help with the translation of the program into other languages.

Arguments for the command line:
/lang= - set the language of the program starts. Example: /lang=en
/deleteapp= - allows you to delete an application Metro in Windows. Example: /deleteapp=bing or /deleteapp=note
/destroy - an argument for removing spyware.
IMPORTANT! Arguments /destroy and /deleteapp= can not be combined, and the argument /deleteapp= can not be used several times.

**Comment by Nummer** [comment]
@vpm ok.
 TODO: Add
