### ISSUE TITLE
Не стартует "Служба наблюдения за датчиками" (SensrSvc)

### ISSUE THREAD

**Issue by Hyper43** [Nummer/Destroy-Windows-10-Spying#219]
Добрый день
После "SetRegValueHklm(@"SOFTWARE\Policies\Microsoft\Windows\LocationAndSensors",  DisableSensors", "1", RegistryValueKind.DWord);" перестает запускаться служба SensrSvc, из за чего ноутбут-трансформер превращается в... просто ноутбук (не реагирует на датчик положения экрана и другие датчики), что немного огорчает. Возможно отключение датчиков не обязательно для отключения шпионства в Win10, если нет, то думаю лучше предупредить пользователя, помимо прочего, и о подобных последствиях.

**Comment by Pegas1606** [comment]
I am I got a problem with me numb tablet sensor for sensing auto rotation. It's in the items prohibited in your privacy settings. And I think the position detection. Once I wrote about this issue and has not been repaired. For jišťování position is, in my opinion, unnecessarily natrvrdo off everything and even when I turned on the sensors in registries tablets continue unresponsive. I need to know what specifically turn off the location and how to fix it. They could add at least one box position detection separately so that the owners of these devices with rotating atomatickým no trouble or at least the possibility of returning, and I do not mean through the recovery point system because it does not always succeed.

**Comment by Pegas1606** [comment]
Based positioning shit I find without a GPS device, which most computers and not by IP as a maximum, must Prague with me even though I live somewhere else if I do not have a fixed IP. (LTE router).

**Comment by Pegas1606** [comment]
Nezbývá nic jiného než použít vše kromě zakázat v nastavení soukromí. No a ten zbytek si vypnout sám v přes jednotlivé položky a telemetrii v registrech, nebo přes správu služeb. To mě tedy, ale pěkně sere. Minule jsem takhle v domění, že je chyba automatického otáčení opravena asi musel přeinstalovat tablet ze 16GB úložiště, což není jednoduchá záležitost. Mnoho kabelů, usb hub, klávesnice, myš, čtečka karet, protože ta vestavěná je ti na instalaci Windows na nic atd.

**Comment by Pegas1606** [comment]
We have no choice but to use everything except disabled in your privacy settings. Well, the rest can turn it off at over individual items and telemetry in registers or through management services. That to me then, but pretty pissed off. Last time I was in this domain from the error corrected automatic rotation about having to reinstall the tablet 16 gigabytes of storage, which is not a simple matter. Many cables, usb hub, keyboard, mouse, card reader, because it is built into the Windows installation etc. anything.

**Comment by Nummer** [comment]
fixed
