### ISSUE TITLE
Please include all basic WiFI/LAN drivers.

### ISSUE THREAD

**Issue by omegaflare** [Nummer/Destroy-Windows-10-Spying#246]
One of my friend was having extraordinary difficulties installing WiFi driver -- he's incompetent, so I had to help.

Bottom line, please include ALL BASIC WIFI/LAN drivers. For example: Intel, Broadcom, Atheros, and others.

Cool? Thanks.

**Comment by omegaflare** [comment]
A friend of mine broadcom drivers and apparently Windows 10 doesn't support it; he wasn't able to turn on WiFi via setting, it just rubberband it from on to off - was it intentional on your part?

**Comment by Xanarkan** [comment]
I don't see any relate with DWS here ... it's a software that delete the spying features of Windows 10, it doesn't install anything. So ... no ?

**Comment by Wohlstand** [comment]
Why not to make a pack yourself? (include into it the DWS and full set of drivers you needed, then just pack everything into ISO (to be able plug it into virtual machine) and share via any public service like Google Drive or Yandex Disk, Dropbox is not recommended for this because very small lifetime of the links)
