### ISSUE TITLE
Critical bug: the tool does not work without Internet access

### ISSUE THREAD

**Issue by manad777** [Nummer/Destroy-Windows-10-Spying#288]
UPDATE:I appreciate Nummer's effort, but this tool is unmaintained.  I suggest people use Spybot Anti-Beacon instead of this tool. It works offline, and does more things. 

Running DWS_Lite.exe with no Internet access crashes at startup, with the message "error check update". It tries to connect to raw.githubusercontent.com and fails.

This tool should be fully functional offline. In fact, the recommended way of using it should be to apply it to a fresh Windows install that has never been connected to the Internet.

**Comment by Wohlstand** [comment]
That is not good to don't catch error of networking which is very optional here. Especially self-updates.

**Trivia:** I never trust Win10 and I don't connect it until apply this (made a dummy I so with it and plugged to virtualbox). 

**Fun fact:** when my colleague installed it to his machine, first Win10 tried to do - download/upload it's evil stuff, and overloaded network channel, so, my Thunderbird even failed to find server to check mail... That crap was gone since I physically unplugged his machine from the switch.
