### ISSUE TITLE
Bad default options

### ISSUE THREAD

**Issue by zeroZshadow** [Nummer/Destroy-Windows-10-Spying#96]
The app disables windows updates by default, it really shouldn't
This will leave you open to security issues, even if this does mean windows can install something new on your pc.

It should be off by default
Same for windows defender (why is this even disabled?)

**Comment by BourbonCrow** [comment]
Well has windows defender ever protected anyone? probably not 60% of viruses or more.. goes through it...
If you feel need to get an anti-virus i would recommend something else.
+ It's probably disabled since i think it uploads as they call is suspicious files to Microsoft (not sure)

But yes Windows update should be on by default.

**Comment by zeroZshadow** [comment]
Yes it has protected people? Me for instance, defender works fine.
It might not be as good as the others, but the issue here is that is turned off by DEFAULT.
While the option is hidden under "professional mode"

Especially considering they arn't sure if defender even does anything bad
And since there is no simple undo feature (besides a system restore, which is broken en problematic when you only find the issues after a few days)
